server:
  shutdown: graceful
spring:
  application:
    name: orderservice

  batch:
    job:
      enabled: false # prevent job trigger on app start
    jdbc:
      initialize-schema: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/order-service
    username: postgres
    password: postgres

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: drop-and-create
job:
  order:
    cron: 0 */5 * ? * * # every 5 minutes